name: "Publish"
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: jameshenry/publish-action@v0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
